export PATH="$PATH:$HOME/bin"
export GIT_PATH="/data/git"
export DOT_FILES="$GIT_PATH/dotfiles"
export XDG_DESKTOP_DIR="$HOME"
export XDG_DOWNLOAD_DIR="$HOME/download"
export XDG_CONFIG_HOME="$HOME/.config"
