#!/bin/bash

spacesfilter='map({key: .id | tostring, value: .windows}) | from_entries'
windowfilter='map(tostring) | map({id: ., windows: ($windows[.]//0)})'
socket="/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"

workspaces() {
  spaces=$(hyprctl workspaces -j | jq "$spacesfilter")
  seq 1 10 | jq --argjson windows "${spaces}" --slurp -Mc "$windowfilter"
}

workspaces
socat -u UNIX-CONNECT:"$socket" - | while read -r line; do
  workspaces
done
