#!/bin/sh

workspaces() {
  spaces=$(hyprctl workspaces -j | jq "map({ key: .id | tostring, value: .windows }) | from_entries")
  seq 1 10 | \
    jq --argjson windows "$spaces" --slurp -Mc "map(tostring) | map({ id: ., windows: 0 })"
}

socat -u UNIX-CONNECT:"$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - | while read -r lines; do
  workspaces
done
